Milestone5 feature branch
SunnySparks/ror-social-scaffold pull request #4
Opened 2021-07-04 01:02 UTC by SunnySparks

In this pull request, I:

-Created the correct associations for making friendships in social media app by following best practices.

2021-07-05 15:09 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hello @SunnySparks, you have made a great effort so far. The design of your friendships model is good to tackle the task at hand, however, there are a number of fixes you need to apply before this milestone is approved. Kindly check the comments below ⬇️ 

## [OPTIONAL]

- [ ] In addition to all comments, kindly add a link to direct users to friendships.
- [ ] Add some logic that will not allow users to send another request if It already exists(you could not show Add Friend).


Request another code review once you have applied the requested changes.

*Feel free to contact me if you have any questions, All the best 💪 *


> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/users_controller.rb
> +    @user = User.find_by(params[:user_id])
Remove this search for a user instance, it is not necessary for the index action.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/users_controller.rb
>      @users = User.all
This query makes your view include the current user that is logged in along with other users. Create a query that shows all users excluding the current user.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/users_controller.rb
>      @posts = @user.posts.ordered_by_most_recent
This show method should take the correct params passed from the frontend, you are passing ":user_id" that is not existent in the params. It should be params[:id] instead.

2021-07-05 15:09 UTC, Elbie-em commented on app/models/user.rb
> +
This association "has_many :friends" has no reference to any model or alias. Kindly fix this.
*Note: Your current friendship model pretty much covers the requesting friends functionality*
If you want to enforce a friends model, kindly do it correctly.

2021-07-05 15:09 UTC, Elbie-em commented on app/models/user.rb
>  end
The methods created above I see have to work around dealing with the creating, accepting, rejecting, and viewing requests, however, I don't see anywhere in the application they have been used, I additionally see a calling of "inverse_friendships" and it is not clear where it is being referenced from.

2021-07-05 15:09 UTC, Elbie-em commented on app/views/friendships/_friendships.html.erb
> +</small>
This piece of code should be inside the loop as you want to show this for every request that is sent to the user.

2021-07-05 15:09 UTC, Elbie-em commented on app/views/friendships/_friendships.html.erb
> +  <tr>
This is a partial and you are calling a loop to an instance variable, kindly fix this.

2021-07-05 15:09 UTC, Elbie-em commented on config/routes.rb
> +  devise_for :friendships
Devise should be used for creating a user resource, you are calling to create an auth resource for the friendships model, this is incorrect, kindly nest the friendship resource in the correct resource.

2021-07-05 15:09 UTC, Elbie-em commented on app/views/users/_user.html.erb
>    </span>
This post request is referencing a user instance within a partial. you should only reference the friend being user.id as params as your controller already references the current user as user_id when creating a request.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +    @user = User.find_by(params[:user_id])
This user_id param causes your application to always find the first user as it does not exist. Kindly fix this by searching for the current_user with current_user.id

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +  end
This is a requests page and should load all requests sent to this user, kindly fix this by querying the database for friendships that have the current user's id and the friend_id.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +end
Your accept method causes your application to break as it has references to methods that do not exist.
".status is not a field in the friendships table". Kindly fix this logic

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +  end
The "decline" method is not present anywhere in your application, kindly enforce the destroy logic correctly.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +    @friendship.save!
When creating a friendship, your arguments should correspond to your params, in this case, friend_id should reference params[:friend_id] and not user_id which is unexistent.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +
From your logic and inspection of your model, you should create the inverse friendship from here. You can generate a method on your model to do this and create a call back that creates the inverse friendship. 
What this means is once confirmed for a friendship is "true", create another friendship by reversing the id's for user and friend and both entries should be true.
e.g user_id: 1 friend_id: 2 confirmed: true <=====> user_id: 2 friend_id:1 confirmed: true.

2021-07-05 15:09 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +end
There is a continuous incorrect reference for the current_user id as user_id, kindly fix this in all places I have indicated.

2021-07-05 15:09 UTC, Elbie-em commented on app/views/friendships/_friendships.html.erb
> +  </tr>
When this is corrected, your iteration should a ruby object, kindly search for the user who has send this request and display their name instead.

2021-07-14 23:58 UTC, george-shammar requested changes
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

@SunnySparks , you're making decent effort. :+1: 
:heavy_check_mark: Your repo looks professional without linter errors and you've also worked with the correct gitflow.

**To improve** :hammer_and_pick: :construction_worker: 

- [x] A lot of the required changes from the previous review have not been implemented. I encourage you to re-visit the comments and tick them off one at a time. Please don't be frustrated, you're almost there. 

This is the reason your friendship feature is not functional. Currently, two users could send friendship request to each other countless times. Friendship can not be confirmed nor declined.

Please, if you need help, ask for it early. 

[OPTIONAL]

- [ ] I saw just three test examples. Please write tests for associations, validations and integration.

Please submit another CRR when you're ready.

Cheers :smile: With respect :tophat:

2021-07-17 00:33 UTC, carlos-ssh approved these changes
Hola, @SunnySparks:  

 ¡Tu proyecto está completo! No hay nada más que decir aparte de ... es hora de fusionarlo: shipit:  
 ¡Felicidades! 🎉  



 ¡Salud y codificación feliz! 👏👏👏 

 No dude en dejar cualquier pregunta o comentario en el hilo de relaciones públicas si algo no está 100% claro. 


 ------ 
 _ Como se describe en la [Política de límites de revisiones de código] (https://microverse.zendesk.com/hc/en-us/articles/1500004088561), solo tiene 3 revisiones de código por proyecto. Si cree que la revisión del código no fue justa, puede solicitar una segunda opinión utilizando [este formulario] (https://airtable.com/shrQAqnBwek5a0O0s) ._

2021-07-17 19:17 UTC, merged